# Generated by Django 2.2.7 on 2019-12-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smash', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='image',
            name='imagen',
            field=models.FileField(blank=True, upload_to='img'),
        ),
    ]
