# Generated by Django 2.2.7 on 2019-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smash', '0003_auto_20191203_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='foto_usuarios')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado_actual', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='imagen',
            field=models.ImageField(upload_to='img'),
        ),
    ]
